### ISSUE TITLE
NavigationブロックのSubmenuカラーが効かないので詳細度を上げる必要がある

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/vk-color-palette-manager#16]
Submenu & overlay text
Submenu & overlay background
が効かない
![submenu](https://user-images.githubusercontent.com/42362903/195745645-e52460e2-7f7b-4530-a4b2-e42802860fc2.png)

コアでは
`.has-luminous-vivid-amber-color{color: var(--wp--preset--color--luminous-vivid-amber) !important;}`
のようなcssが出力されているので!importantを付ける必要がある
https://github.com/WordPress/wordpress-develop/blob/90a7ecc47472664baef43935718471bf9e08cfac/src/wp-includes/class-wp-theme-json.php#L1335-L1336

**Comment by kurudrive** [comment]
@shimotmk お疲れ様ですー🖐

これ僕の環境では

* サイトエディタ : そもそもカスタムカラーパレットが表示されない...
  ※これはこれで問題かもしれないけど、いやもうtheme.jsonでええやん感はあるよね...
* 記事本文への配置 : 普通に色は反映される

という感じでとりあえず僕の環境でも再現させたいのですが

* 症状が発生したテーマ
* 確認した場所はサイトエディタ？本文欄？

をよろしくお願いいたしますー (￣人￣)

**Comment by shimotmk** [comment]
@kurudrive 
わかりにくく、スミマセン
環境はこのような形です
WP6.0
テーマLightning
プラグインVK Blocks  Proのみ

https://user-images.githubusercontent.com/42362903/196362265-75dc20de-0831-4765-8439-97e19d160fad.mp4

サブメニューを作ったときのテキストカラーと背景色です

**Comment by kurudrive** [comment]
@shimotmk あー！オーバーレイの意味を理解してませんでした！症状確認しました！

**Comment by shimotmk** [comment]
closed this as completed in #19
