### ISSUE TITLE
has-${色名}-border-color クラスがほしいかも

### ISSUE THREAD

**Issue by drill-lancer** [vektor-inc/vk-color-palette-manager#4]
has-border-color  has-${色名}-border-color みたいな使い方を想定

**Comment by kurudrive** [comment]
必要なんじゃないかと思いつつ、コアでそのクラスを使っている場面がまだ見かけてないので追加していない状態です。
コアだと is-style-outline をつけてて、それがついてると 線の色に 
border-bottom: 1px solid currentColor; 
を指定している感じです。

**Comment by shimotmk** [comment]
@kurudrive 
WordPress 5.9からhas-${色名}-border-colorが追加されました
なので @drill-lancer さんの予言どおり、このクラス名は必要だと思うのですがいかがでしょうか？
https://github.com/WordPress/gutenberg/pull/30124

コアのプルクオートなどで使われています

**Comment by kurudrive** [comment]
@drill-lancer @shimotmk あった方が良いと思いますー。追加でよろしくお願いいたします。
