### ISSUE TITLE
テーマが Lightning pro のとき、パレットにキーカラーが表示されない

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-color-palette-manager#9]

**Comment by sysbird** [comment]
テーマが Lightning pro のとき、パレットにキーカラーが表示されないようです
カラーパレット設定のカスタムカラー 1-5は表示されます

- [ ] 5.8
- [ ] 5.9

**Comment by shimotmk** [comment]
マージされているのでcloseします

**Comment by kurudrive** [comment]
|・ｗ・）.oO（ あ、実はそのあと Revert してるのですよ... ）

**Comment by shimotmk** [comment]
あ、すみません。そうですね
